"""Add screenshot_url to applications table

Revision ID: 78f94bbb861e
Revises: ed3b9e85d5f6
Create Date: 2025-04-21 17:24:11.089474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f94bbb861e'
down_revision: Union[str, None] = 'ed3b9e85d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('screenshot_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'screenshot_url')
    # ### end Alembic commands ### 