"""Replace auth0_sub with supabase_user_id in users table

Revision ID: 968f67fbf361
Revises: 78f94bbb861e
Create Date: 2025-04-22 15:28:06.895459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968f67fbf361'
down_revision: Union[str, None] = '78f94bbb861e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_users_auth0_sub', table_name='users')
    # op.drop_index('ix_users_supabase_id', table_name='users') # Commented out potentially leftover drop
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    # op.drop_column('users', 'supabase_id') # Commented out potentially leftover drop
    op.drop_column('users', 'auth0_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_sub', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('supabase_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.create_index('ix_users_supabase_id', 'users', ['supabase_id'], unique=True)
    op.create_index('ix_users_auth0_sub', 'users', ['auth0_sub'], unique=True)
    op.drop_column('users', 'supabase_user_id')
    # ### end Alembic commands ### 