"""Check for schema differences

Revision ID: ed3b9e85d5f6
Revises: ae31ea6ff78b
Create Date: 2025-04-21 11:16:58.968082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3b9e85d5f6'
down_revision: Union[str, None] = 'ae31ea6ff78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 