import React from 'react';

const AiDisclosurePage = () => {
  return (
    // Removed Layout wrapper as it's handled by root layout
    <div className="container mx-auto px-4 py-8 pt-24"> {/* Added pt-24 for spacing below navbar */}
      <h1 className="text-3xl font-bold mb-6">AI Disclosure</h1>
      <p className="mb-4">Last Updated: April 19, 2025</p>

      <h2 className="text-2xl font-semibold mt-6 mb-3">1. Introduction</h2>
      <p className="mb-4">
        Transparency is important to us at OpenCrew ("we," "us," or "our"). This AI Disclosure explains how we utilize artificial intelligence (AI) and automated systems within our website and services (collectively, the "Service"). Our goal is to leverage these technologies responsibly to enhance your job search experience.
      </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">2. AI-Powered Features</h2>
        <p className="mb-4">
          We employ AI and automated systems in the following key features of our Service:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Resume Optimization Assistance:</strong> We use AI systems to analyze the text content of your resume and provide suggestions for improvement, such as alternative phrasing or highlighting potentially relevant skills based on general best practices or specific job descriptions.
          </li>
          <li>
            <strong>Job Matching:</strong> We utilize semantic analysis technology (a form of AI) to compare the content of your resume(s) and profile information against the descriptions of job postings collected by our Service. This helps identify and rank job opportunities that may be relevant to your skills and experience based on semantic similarity.
          </li>
          <li>
            <strong>Automated Application Assistance:</strong> For users who opt-in to our Auto-Application Feature (as detailed in our Terms of Service), automated systems, potentially including semantic analysis technology, are used to help identify and populate form fields on external job application websites using the data you provide within our Service.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">3. Data Used by AI Systems</h2>
        <p className="mb-4">
          The AI and automated systems described above primarily process the following types of data:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Resume Content:</strong> The text, structure, and metadata contained within the resume documents or text you upload or input into the Service.
          </li>
          <li>
            <strong>Job Descriptions:</strong> The text, requirements, and metadata from job postings collected by our Service.
          </li>
          <li>
            <strong>User Profile Information:</strong> Information you provide in your user profile that is relevant to job matching (e.g., skills, experience summaries).
          </li>
          <li>
            <strong>User-Provided Data for Auto-Application:</strong> Personal details and work history information you provide and authorize for use with the Auto-Application Feature.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">4. Data Sharing with AI Service Providers</h2>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Resume Optimization:</strong> To provide the resume optimization assistance feature, we may transmit portions (snippets) of your resume text to a third-party AI service provider. This provider processes the text solely to generate suggestions for our Service to display to you. We take steps to send only the necessary information for this purpose.
          </li>
          <li>
            <strong>Job Matching & Auto-Application Field Assistance:</strong> The semantic analysis technology used for job matching and assisting with field identification during auto-application is primarily processed using systems under our control or hosted infrastructure managed on our behalf. While this may involve third-party infrastructure (like cloud hosting or specialized databases), the core analysis models for these specific functions are typically operated internally or within our direct technical environment, distinct from sharing raw text snippets with external AI model providers for generative tasks like resume rewriting.
          </li>
        </ul>
        <p className="mt-4 mb-4">
          Please refer to our Privacy Policy for more comprehensive details on data sharing with third-party service providers.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">5. How AI Output is Used</h2>
        <p className="mb-4">
          The output generated by our AI systems is used within the Service to:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>Provide you with suggestions to potentially improve your resume content.</li>
          <li>Rank and present job postings that are semantically similar to your profile.</li>
          <li>Assist in identifying corresponding fields on external application forms when using the Auto-Application Feature.</li>
        </ul>
        <p className="mb-4">
          The AI does not make hiring decisions or guarantee employment outcomes. It serves as a tool to assist you in your job search process.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">6. Limitations and User Responsibility</h2>
        <p className="mb-4">
          While we strive to develop and implement effective AI systems, it's important to understand their limitations:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Accuracy:</strong> AI outputs, such as resume suggestions or job matches, may not always be perfectly accurate, complete, or suitable for every situation. Semantic understanding has limitations, and interpretations may vary.
          </li>
          <li>
            <strong>Bias:</strong> AI systems can potentially reflect biases present in the data they were trained on. We work to mitigate bias, but it cannot be entirely eliminated.
          </li>
          <li>
            <strong>No Guarantees:</strong> The use of AI features does not guarantee job interviews, job offers, or any specific career outcome. Success in the job market depends on numerous factors beyond the scope of our AI tools.
          </li>
          <li>
            <strong>User Review Required:</strong> You are ultimately responsible for reviewing any AI-generated suggestions (e.g., resume edits) and verifying the accuracy and appropriateness of information used or submitted via automated features (e.g., Auto-Application). Human judgment should always be applied.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">7. Updates to this Disclosure</h2>
        <p className="mb-4">
          We may update this AI Disclosure from time to time as our use of AI technology evolves. We will notify you of significant changes by posting the updated disclosure on our Service and updating the "Last Updated" date.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">8. Contact Information</h2>
        <p className="mb-4">
          If you have questions about our use of AI, please contact us at: support@opencrew.io
        </p>
      </div>
    // Removed Layout wrapper
  );
};

export default AiDisclosurePage;
